[package]
name = "kernel-asound-sys"
version = "0.1.0"
authors = ["David Henningsson <diwic@ubuntu.com>"]
description = "ALSA kernel bindings (bindgen generated). You probably want the ALSA crate instead."

[dependencies]
nix = "0.11"

[build-dependencies]
bindgen = "0.43.1"
regex = "1"
